config/routes.rb
Rails.application.routes.draw do
  #home
  root to: 'gossips#index'

  #pages menu
  get '/team', to: 'pages#team'
  get '/contact', to: 'pages#contact'
  get '/inscription', to: 'pages#inscription'
  get '/connexion', to: 'pages#connexion'

  #gossips
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  #users
  resources:users, only: [:create, :show]

  #cities
  resources:cities, only: [:show]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 3, too_short: "%{count} characters is the minimum allowed", maximum: 14, too_long: "%{count} characters is the maximum allowed" }
  validates :content,
    presence: true
  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
  has_many :comments
  has_many :users, through: :comments
end

app/models/join_pm_receiver.rb
class JoinPmReceiver < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_pm_receivers
  has_many :recipients, class_name: "User", through: :join_pm_receivers
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :comments
  has_many :gossips, through: :comment
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
  validates:password,presence: true,length:{minimum: 6}
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @current_city = City.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def team
  end

  def inscription
  end

  def connexion
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @current_user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <%= link_to "The Gossip Project", root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item <%= 'active' if current_page?(root_path) %>">
            <%= link_to "Accueil", root_path, :class => "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(team_path) %>">
            <%= link_to "Team", team_path, :class => "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(inscription_path) %>">
            <%= link_to "inscription", inscription_path, :class => "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(connexion_path) %>">
          <%= link_to "Connexion", connexion_path, :class => "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(contact_path) %>">
        <%= link_to "Contact", contact_path, :class => "nav-link" %>
      </li>
        </ul>
        
      </div>
    </nav>
    <header class="container ">
      <%= link_to root_path do %>
        <%= image_tag "/images/banner.png" %>
      <% end %>
    </header>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/connexion.html.erb
<body class="text-center">
    <form class="form-signin">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
  <label for="inputEmail" class="sr-only">Email address</label>
  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required=""><label for="inputPassword" class="sr-only">Password</label>
  
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted">© 2018-2020</p>
</form>


</body>

app/views/pages/contact.html.erb
  <h1>
    Contact : Luca Montaigut
  </h1>

<main class="container">
  <h2>Vous pouvez me contacter sur : </h2>
  <ul>
    <li><a href="mailto:lmontaigut@gmail.com">lmontaigut@gmail.com</a></li> 
    <li> 06.73.82.53.32 </li> 
    <li><a href="https://github.com/luca-montaigut">https://github.com/luca-montaigut</a></li> 
  </ul>
</main>

app/views/pages/inscription.html.erb
<h1> Inscriez-vous</h1>

<body class= "text-center"
    <form action= <%= gossips_path %> method="POST">
        Email adress : <input type="text" name="email">
    </form>
    <p>         </p>

    <form>
        Password :
        <input type="text" name="password">
        Comfirmation password :
        <input type="text" name="confirmation_password">
    </form>
    <p>         </p>

    <form>
        Country :
        <input type="text" name="country">
    </form>
    <p>         </p>

    <input type="submit" value="valider">

</body>

app/views/pages/team.html.erb
<main class="container my-5" style="margin-top : 20px;">
  <div class="card-deck">
    <div class="card text-center bg-light my-3 mx-3" style="border:none; text-align:right;">
      <img id="bibi" class="card-img-top rounded-circle" src="/images/profil.jpeg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Luca Montaigut</h5>
        <p class="card-text">Developpeur débutant chez THP</p>
      </div>
    </div>

    <div class="card text-center bg-light my-3 mx-3" style="border:none;">
      <img id="alfred" class="card-img-top rounded-circle" src="/images/alfred.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Alfred</h5>
        <p class="card-text">Mon fidèle poisson combattant, assistant quotidien et soutien sans faille dans la galère.</p>
      </div>
    </div>
  </div>
</main>
<footer id="lazyrabbit">
  <div>
    <p>  (\(\</p>
    <p>  ( -.-)</p>
    <p>  o_(")(")</p>
  </div>  
</footer>